auto: true
pygments: true
paginate: 1
abstract_size: 150

disqus: true
title : TIL
tagline: Today I Learned...
author :
  name : Anton Khodakivskiy
  email : akhodakivskiy@gmail.com
  github : akhodakivskiy
  twitter : akhodakivskiy
