pygments: true
paginate: 5

disqus: true
title : TIL
tagline: Today I Learned...
author :
  name : Anton Khodakivskiy
  email : akhodakivskiy@gmail.com
  github : akhodakivskiy
  twitter : akhodakivskiy
